import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { config } from '@fortawesome/fontawesome-svg-core'; 
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false; // Auto CSS injection stop karein
import { 
  faMagnifyingGlass, 
  faHeart, 
  faCartShopping, 
  faUser,
  faSun,
  faMoon,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faEnvelope,
  faLocationDot,
  faShieldHalved,
  faTruckFast,
  faRotateLeft,
  faClock,
  faBriefcase,
  faCrown,
  faStar,
  faArrowRight,
  faGem,
  faTag,
  faBars,
  faXmark,
  faHouse,
  faStore,
  faLayerGroup,
  faCircleInfo,
  faPhone,
  faHeadset
} from '@fortawesome/free-solid-svg-icons';

export {
  FontAwesomeIcon,
  faMagnifyingGlass,
  faHeart,
  faCartShopping,
  faUser,
  faSun,
  faMoon,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faEnvelope,
  faLocationDot,
  faShieldHalved,
  faTruckFast,
  faRotateLeft,
  faClock,
  faBriefcase,
  faCrown,
  faStar,
  faArrowRight,
  faGem,
  faTag,
  faBars,
  faXmark,
  faHouse,
  faStore,
  faLayerGroup,
  faCircleInfo,
  faPhone,
  faHeadset
};