import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { 
  faMagnifyingGlass, 
  faHeart, 
  faCartShopping, 
  faUser,
  faSun,
  faMoon,
  faChevronDown,
  faPhone,
  faEnvelope,
  faLocationDot,
  faShieldHalved,
  faTruckFast,
  faRotateLeft,
  faClock,
  faBriefcase,
  faCrown,
  faStar,
  faArrowRight,
  faGem,
  faTag,
  faBars,
  faXmark
} from '@fortawesome/free-solid-svg-icons';

export {
  FontAwesomeIcon,
  faMagnifyingGlass,
  faHeart,
  faCartShopping,
  faUser,
  faSun,
  faMoon,
  faChevronDown,
  faPhone,
  faEnvelope,
  faLocationDot,
  faShieldHalved,
  faTruckFast,
  faRotateLeft,
  faClock,
  faBriefcase,
  faCrown,
  faStar,
  faArrowRight,
  faGem,
  faTag,
  faBars,
  faXmark
};